"""empty message

Revision ID: 0033b335e1ef
Revises: 2c4702143999
Create Date: 2023-10-15 10:37:28.542776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0033b335e1ef'
down_revision = '2c4702143999'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievements',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('achievements_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['achievements_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_achievements')
    # ### end Alembic commands ###