"""empty message

Revision ID: 497911334019
Revises: dec9147bdec8
Create Date: 2023-10-14 17:22:26.121136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497911334019'
down_revision = 'dec9147bdec8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('coins', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'xp')
    op.drop_column('users', 'coins')
    op.drop_column('users', 'level')
    # ### end Alembic commands ###