"""empty message

Revision ID: 4bd84cd9eeab
Revises: c39715ec83f7
Create Date: 2023-10-15 04:19:23.846425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd84cd9eeab'
down_revision = 'c39715ec83f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_badges',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('badge_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_badges')
    # ### end Alembic commands ###