"""empty message

Revision ID: 56cbfe15dd39
Revises: c000646a3582
Create Date: 2023-10-15 09:56:55.183816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cbfe15dd39'
down_revision = 'c000646a3582'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###