"""empty message

Revision ID: 572e7d4a5479
Revises: 4bd84cd9eeab
Create Date: 2023-10-15 04:23:51.124166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572e7d4a5479'
down_revision = '4bd84cd9eeab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('colour', sa.String(), server_default='#000000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badges', 'colour')
    # ### end Alembic commands ###