"""empty message

Revision ID: 8d3536885e36
Revises: 7b4f2f2784fe
Create Date: 2023-10-15 06:32:07.517886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3536885e36'
down_revision = '7b4f2f2784fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('progress_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'achievements', 'progress', ['progress_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.drop_column('achievements', 'progress_id')
    # ### end Alembic commands ###