"""empty message

Revision ID: dec9147bdec8
Revises: c6c142dbc581
Create Date: 2023-10-14 17:07:27.451600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec9147bdec8'
down_revision = 'c6c142dbc581'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###