"""empty message

Revision ID: ec8ca72b7db8
Revises: 806827d31c71
Create Date: 2023-10-15 03:42:19.295606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8ca72b7db8'
down_revision = '806827d31c71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###