"""empty message

Revision ID: ff4eb76a5791
Revises: 4e4fc62cfebf
Create Date: 2023-10-14 16:31:51.652826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4eb76a5791'
down_revision = '4e4fc62cfebf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###